2024-10-02 10:23:17,859 (34433/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-02 10:23:17,860 (34433/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-02 10:23:17,863 (34433/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-10-02 10:23:27,940 (34488/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-02 10:23:27,940 (34488/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-02 10:23:27,943 (34488/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-10-02 10:23:32,807 (34515/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-02 10:23:32,807 (34515/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-02 10:23:32,809 (34515/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-10-02 10:23:59,832 (34607/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-02 10:23:59,832 (34607/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-02 10:23:59,893 (34607/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 15432 failed: FATAL:  role "mkhoatd" does not exist\n'
2024-10-02 10:25:09,533 (34735/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-02 10:25:09,534 (34735/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-02 10:25:09,559 (34735/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 15432 failed: FATAL:  role "postgres" does not exist\n'
2024-10-02 10:26:15,053 (35142/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-02 10:26:15,054 (35142/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-02 10:26:16,008 (35161/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-02 10:26:16,008 (35161/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-02 10:26:21,416 (35185/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-10-02 10:26:21,416 (35185/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-10-02 10:26:25,257 (35185/MainThread) pgcli.pgexecute ERROR - sql: 'ls', error: SyntaxError('syntax error at or near "ls"\nLINE 1: ls\n        ^')
2024-10-02 10:26:25,259 (35185/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "ls"\nLINE 1: ls\n        ^\n'
2024-10-02 10:27:40,583 (35185/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) l', error: SyntaxError('syntax error at or near "l"\nLINE 1: EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) l\n                                                                ^')
2024-10-02 10:27:40,583 (35185/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "l"\nLINE 1: EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) l\n                                                                ^\n'
2024-10-02 10:27:44,385 (35185/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) select * from public.wallets.schema_migration', error: FeatureNotSupported('cross-database references are not implemented: "public.wallets.schema_migration"\nLINE 1: ...STS, VERBOSE, BUFFERS, FORMAT JSON) select * from public.wal...\n                                                             ^')
2024-10-02 10:27:44,385 (35185/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.1.0_1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.FeatureNotSupported: cross-database references are not implemented: "public.wallets.schema_migration"\nLINE 1: ...STS, VERBOSE, BUFFERS, FORMAT JSON) select * from public.wal...\n                                                             ^\n'
